version: "3.8"

services:

  # Postgres
  stori-db:
    image: postgres
    container_name: stori-db
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data/
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    environment:
       - POSTGRES_DB=db_stori
       - POSTGRES_HOST=localhost
       - POSTGRES_PORT=5432
       - POSTGRES_USER=db_user
       - POSTGRES_PASSWORD=db_pass
    ports:
      - 5432:5432
    expose:
      - 5432

  # Lambda fuction
  stori-lambda:
    build: .
    container_name: stori-lambda
    environment:
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - POSTGRES_DB=db_stori
      - POSTGRES_HOST=stori-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
    volumes:
      - ./src:/var/task
    ports:
      - 8080:8080
    expose:
      - 8080
