version: "3.8"

services:

  # Postgres
  db:
    image: postgres
    container_name: stori-db
#    env_file:
#      - env.dev
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data/
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
#    networks:
#      - main  # Add the container to the network "main"
    environment:
       - POSTGRES_DB=db_stori
       - POSTGRES_USER=db_user
       - POSTGRES_PASSWORD=db_pass
    ports:
      - 5432:5432
    expose:
      - 5432

  # Lambda fuction
  lambda:
    build: .
    container_name: stori-lambda
    environment:
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    volumes:
      - ./src:/var/task
    ports:
      - "8080:8080"
    expose:
      - 8080
