version: "3.8"

services:
  lambda:
    build: .
    container_name: stori-test
    environment:
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    volumes:
      - ./src:/var/task
    ports:
      - "8080:8080"
    expose:
      - 8080
